saveExact: true
minimumReleaseAgeExclude:
  - "@exadev/eslint-config"
allowBuilds:
  '@anthropic-ai/claude-code': true
  esbuild: true
overrides:
  eslint-plugin-jsdoc: "64.3.6"
  conventional-changelog-writer: "9.2.1"
  qs: "6.15.2"
